### ISSUE TITLE
Style of PyKwiki 2 has several issues

### ISSUE THREAD

**Issue by phayz** [nullism/pykwiki#15] opened 2015-12-16 21:08 UTC
I just created a new, default site with PyKwiki and found two problems (IMO):

1. The layout of the footer doesn't scale well when the browser's window is rescaled. In fact, it's partially "outside" the window, becoming visible only when the window is scaled to be very large.
2. The default colors applied to the navigation bar do not have good contrast. Dark green on a lighter green background makes it hard to read the text.

**Comment by nullism** [comment] 2015-12-16 21:59
Hey Phayz,

Thanks again for all the feedback. I've made several tweaks to the existing style (and adding a few new ones) this week; they'll be on pip by the end of the week.

You can preview the coming default style here: [pykwiki.nullism.com](http://pykwiki.nullism.com/) -- let me know if you think it still has the contrast issues. 

What browser are you using? The footer seems fine on Chrome, but more testing is definitely needed.

**Comment by phayz** [comment] 2015-12-16 23:40
Thanks for the fast reply.

My concern about contrast is only valid (if at all) when the menu items are not active. When each menu item is hovered over, the contrast is just fine. I really need to try another theme since I don't really like the new default.

For the footer layout I was testing in both the latest version of Google Chrome, also Opera Beta. The issue in both browsers is that I have a scroll bar, despite the fact that the window is larger than 1024 x 768.

**Comment by nullism** [comment] 2015-12-17 00:49
Understood. Thanks for the information. 

I *think* I've fixed the issue; I cannot reproduce on Chrome Windows, Chrome Linux, or Firefox Linux. 

I'll also add a black & white theme like with Pykwiki 1.0. 

I will close this issue with the commit when I have it tested. Thanks again for the input!

**Comment by phayz** [comment] 2015-12-17 02:51
Thanks. I have attached a screenshot so that you know what I'm seeing.

In this case, there's little content to the page but instead of the footer being completely visible at the bottom of the screen, it's not visible at all and requires scrolling to see it. That seems odd to me.


![screenshot from 2015-12-17 12-49-14](https://cloud.githubusercontent.com/assets/438816/11860075/a46b9738-a4bc-11e5-8a8e-4277f880879d.png)

**Comment by phayz** [comment] 2015-12-17 02:53
On the topic of themes, I'd certainly appreciate a theme that is similar or the same as that of PyKwiki.

Would it be possible to provide a theme "base colour" configuration option? That way the layout aspects of the theme could remain the same, but it would look different because of the different colour. For example, you might have a green, grey and blue option.

**Comment by nullism** [comment] 2015-12-17 03:04
Hey Phayz,

> That way the layout aspects of the theme could remain the same, but it would look different because of the different colour. For example, you might have a green, grey and blue option

You got it! That's a BIG reason I changed Pykwiki to be based on scss/sass. It should allow for very easy customization for a given style. I'm working on adding a style closer to Pykwiki classic, an orange style, a blue style, dark, and a couple more. My target for these is this week/weekend. 

On the subject of the footer. I agree with your assessment. I need to figure out a way to handle sticky footers. I also hope to have this fixed this week.

After I update Pykwiki on pip, you'll need to do the following:

1. Update Pykwiki. (`pip install pykwiki --upgrade`, but I'm sure you knew that). 
2. Install the latest style(s), navigate to your project directory and run `pykwiki style info` to see the available styles, and `pykwiki style install <name>` to install that style (need to add a -f to overwrite a style if you already have it installed in your project). 

Thanks again for the input. It's very much appreciated.

**Comment by phayz** [comment] 2015-12-17 03:11
Awesome! You're way ahead of my on the themeing, which is good. :D

I look forward to testing the new themes, whenever they're available.

**Comment by nullism** [comment] 2015-12-23 16:12
Hey Phayz,

I've added the styles of *classic*, *dark*, and *sapphire*. The footer issue should now be fixed. These styles are available in Pykwiki v2.1.12.

To install all styles, run `pk style install -f`.

To try out a style, change `style: default` to `style: <name>` in config.yaml, then run `pk cache -f`. 

Let me know what you think. There are more styles coming soon.

**Comment by phayz** [comment] 2016-01-04 11:53
First - sorry for the loooong delay in replying.

Second - Thank you for adding those styles. I'll test them on a sample site and see if you've resolved the issues I reported.

**Comment by nullism** [comment] 2016-01-13 15:13
I'm going to resolve this ticket. Checkout http://pykwiki-styles.nullism.com/default/ for style previews. My goal is to keep that site updated with all the new styles being added. If you still feel there are display issues, please let me know. Thanks for the ideas!

**Closed by nullism** 2016-01-13 15:13 UTC

**Comment by phayz** [comment] 2016-01-13 21:43
Great! I love the ability to go to http://pykwiki-styles.nullism.com/default/ and preview to themes available.

If I find any further issues, I'll raise them here in a new issue.
